apiVersion: v1
kind: Service
metadata:
  name: headless-svc-gpu-ccc
spec:
  clusterIP: None
  selector:
    job-name: gpu-job-ccc
---
apiVersion: batch/v1
kind: Job
metadata:
  name: gpu-job-ccc
spec:
  backoffLimit: 0
  completions: 2  # number of GPU pods
  parallelism: 2  # number of GPU pods
  completionMode: Indexed
  template:
    spec:
      subdomain: headless-svc-gpu-ccc
      restartPolicy: Never
      nodeSelector:
        cloud.google.com/compute-class: gpu-l4-spot
      tolerations:
      - key: "nvidia.com/gpu"
        operator: "Exists"
        effect: "NoSchedule"
      containers:
      - name: gpu-job
        image: pytorch/pytorch:2.2.2-cuda12.1-cudnn8-runtime
        ports:
        - containerPort: 29500 # Default port for PyTorch distributed communication
        command:
        - bash
        - -c
        - |
          echo "=== GPU Pod Index: $JOB_COMPLETION_INDEX ==="
          nvidia-smi
          python3 -c 'import torch; print("CUDA Available:", torch.cuda.is_available(), "| GPU Count:", torch.cuda.device_count(), "| Device Name:", torch.cuda.get_device_name(0) if torch.cuda.is_available() else "None")'
          sleep 432000 # 5 days
        resources:
          requests:
            cpu: 2
            memory: 8Gi
            nvidia.com/gpu: 1
          limits:
            cpu: 2
            memory: 8Gi
            nvidia.com/gpu: 1
