apiVersion: ray.io/v1
kind: RayCluster
metadata:
  name: ray-tpu-singlehost-cluster
spec:
  headGroupSpec:
    rayStartParams: {}
    template:
      spec:
        containers:
          - name: ray-head
            image: ray-project/ray:latest
            imagePullPolicy: Always
            env:
            - name: RAY_TRAIN_V2_ENABLED
              value: "1"
            - name: HF_TOKEN
              valueFrom:
                secretKeyRef:
                  name: hf-secret
                  key: hf_token
                  optional: true
            ports:
              - containerPort: 8265  # Dashboard
              - containerPort: 10001 # Client
              - containerPort: 8888  # gRPC
              - containerPort: 8000  # OpenAI API
            resources:
              limits:
                memory: "48Gi"
              requests:
                cpu: "12"
                memory: "48Gi"
  workerGroupSpecs:
    - replicas: 1
      numOfHosts: 1
      groupName: tpu-group
      rayStartParams: {}
      template:
        spec:
          containers:
            - name: ray-worker
              image: ray-project/ray:latest
              imagePullPolicy: Always
              resources:
                limits:
                  memory: "200Gi"
                  google.com/tpu: "8"
                requests:
                  cpu: "48"
                  memory: "200Gi"
                  google.com/tpu: "8"
              env:
                - name: RAY_TRAIN_V2_ENABLED
                  value: "1"
                - name: HF_TOKEN
                  valueFrom:
                    secretKeyRef:
                      name: hf-secret
                      key: hf_token
                      optional: true
          nodeSelector:
            cloud.google.com/gke-tpu-accelerator: tpu-v5-lite-podslice
            cloud.google.com/gke-tpu-topology: 2x4
            cloud.google.com/gke-spot: "true"
          nodeTaints:
            - key: "google.com/tpu"
              operator: "Exists"
              effect: "NoSchedule"
